apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"my-app","type":"frontend"},"name":"my-nginxs","namespace":"default"},"spec":{"containers":[{"image":"nginx:alpine","name":"my-nginxs","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2021-08-10T22:39:20Z"
  labels:
    app: my-app
    type: frontend
  name: my-nginxs
  namespace: default
  resourceVersion: "54351"
  uid: e5121598-75c3-4cb0-a561-251241bcc02d
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: my-nginxs
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8n5g2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-8n5g2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-10T22:39:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-10T22:39:22Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-10T22:39:22Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-10T22:39:20Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c716799e62fec10aac21c1b74faf8b60fe8523180cec7534827c40d23731af64
    image: nginx:alpine
    imageID: docker-pullable://nginx@sha256:bead42240255ae1485653a956ef41c9e458eb077fcb6dc664cbc3aa9701a05ce
    lastState: {}
    name: my-nginxs
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-08-10T22:39:22Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.38
  podIPs:
  - ip: 10.1.0.38
  qosClass: BestEffort
  startTime: "2021-08-10T22:39:20Z"