apiVersion: v1
kind: Pod
metadata:
 name: node-api-server
 labels:
  app: my-node-api-server
  type: backend
spec:
  containers: 
    - name: node-api-server
      image: node-server:latest
      imagePullPolicy: IfNotPresent
      ports: 
      - containerPort: 3000
  env:
  - name: key
    valuefrom: 
      configMapKeyRef:
        name: app-settings 
        key: enemies