apiVersion: v1
kind: Pod
metadata:
 name: my-nginxs 
 labels:
  app: my-app
  type: frontend
spec:
  containers: 
    - name: my-nginxs
      image: nginx:alpine
      ports: 
      - containerPort: 80