apiVersion: batch/v1
kind: Job
metadata:
  name: pie-counter
spec:
  completions: 6
  parallelism: 2
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: pie-counter
    spec:
      containers:
      - name: pi
        image: alpine
        command: ["sh",  "-c", "-wle", "print bpi(2000)"]
      restartPolicy: Never
