apiVersion: v1
kind: Pod
metadata:
 name: my-nginxs 
 labels:
  app: my-app
  type: frontend
spec:
  containers: 
    - name: my-nginx-readiness
      image: nginx:alpine
      resources:
        limits:
          memory: "100Mi"
        requests:
          memory: "50Mi"
      ports: 
      - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1