apiVersion: v1
kind: Pod
metadata:
 name: liveness-demo
 labels:
  app: my-app
  type: server
spec:
  containers: 
    - name: liveness-demo
      image: k8s.gcr.io/busybox
      resources:
        limits:
          memory: "64Mi"
      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 6000
      livenessProbe:
        exec:
          command: 
          - cat
          - /tmp/healthy
        initialDelaySeconds: 15
        periodSeconds: 5
        failureThreshold: 1