apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  annotations:
    volume.beta.kubernetes.io/storage-class: accounthdd
    
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
