apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-server-deploy
  labels:
    app: node-api-server
    tier: api
spec:
  replicas: 4
  minReadySeconds: 10
  selector:
    matchLabels:
      tier: api
  template:
    metadata:
      labels:
        tier: api
    spec:
      containers:
      - name: node-api-server
        image: node-server:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
