apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ps-pv
  annotations:
    Storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
volumeBindingMode: waitForFirstConsumer
parameters:
  type: pd-ssd
  replication-type: none 