apiVersion: v1
kind: PersistentVolume
metadata:
  name: ps-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  storageClassName: ps-fast
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: ps-vol
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
